### ISSUE TITLE
Google Signin issue 

### ISSUE THREAD

**Issue by webdeveloper510** [Mirror-Protocol/mirror-mobile-app#1]
![Screenshot_20210216-151740](https://user-images.githubusercontent.com/7536620/108046304-759edd80-7012-11eb-8cac-9b44f89bb75c.png)
i'm getting this page for copy paste code after google signin . Its not redirecting to my  mirror app .Please help me to solve this

**Comment by bokuhe** [comment]
This is a Google login issue for your personal account, so it would be faster to contact Google. Or can I give more information to help?

**Comment by webdeveloper510** [comment]
Issue has resolved   Thanks
